// @ts-nocheck
// Fallback typed bindings when Rust codegen is unavailable in sandbox.
// Normally this file is generated by tauri-specta.

import { invoke } from '@tauri-apps/api/core'

export type Result<T, E = string> = { status: 'ok'; data: T } | { status: 'error'; error: E }

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | undefined
  | { [key: string]: JsonValue }
  | JsonValue[]

export type RecoveryError =
  | { type: 'FileNotFound' }
  | { type: 'ValidationError'; message: string }
  | { type: 'DataTooLarge'; max_bytes: number }
  | { type: 'IoError'; message: string }
  | { type: 'ParseError'; message: string }

export type AppPreferences = {
  theme: string
  quick_pane_shortcut: string | null
  close_behavior: string
  theme_palette: string
  silent_start: boolean | null
  language: string | null
  auto_start: boolean | null
  mood_candidates: Record<string, string[]> | null
  recording_directory: string | null
  ffmpeg_executable_path: string | null
}

export type SaveParcelRecordingResponse = {
  file_name: string
  file_path: string
  file_size_bytes: number
  deleted_files: string[]
  total_size_bytes: number
}

export type ParcelRecordingItem = {
  file_name: string
  file_path: string
  file_size_bytes: number
  modified_at_ms: number
  barcode: string
}

async function invokeResult<T, E = string>(command: string, args?: Record<string, unknown>): Promise<Result<T, E>> {
  try {
    const data = await invoke<T>(command, args)
    return { status: 'ok', data }
  } catch (error) {
    return { status: 'error', error: error as E }
  }
}

export const commands = {
  greet: (name: string) => invokeResult<string>('greet', { name }),
  loadPreferences: () => invokeResult<AppPreferences>('load_preferences'),
  savePreferences: (preferences: AppPreferences) => invokeResult<void>('save_preferences', { preferences }),
  sendNativeNotification: (title: string, body: string | null) =>
    invokeResult<void>('send_native_notification', { title, body }),

  getParcelRecordingDirectory: () => invokeResult<string>('get_parcel_recording_directory'),
  findParcelRecordingsByBarcode: (barcode: string) =>
    invokeResult<ParcelRecordingItem[]>('find_parcel_recordings_by_barcode', { barcode }),
  saveParcelRecordingMp4: (barcode: string, webmData: number[], maxStorageBytes?: number) =>
    invokeResult<SaveParcelRecordingResponse>('save_parcel_recording_mp4', {
      barcode,
      webmData,
      maxStorageBytes,
    }),

  saveEmergencyData: (filename: string, data: JsonValue) =>
    invokeResult<void, RecoveryError>('save_emergency_data', { filename, data }),
  loadEmergencyData: (filename: string) =>
    invokeResult<JsonValue, RecoveryError>('load_emergency_data', { filename }),
  cleanupOldRecoveryFiles: () => invokeResult<number, RecoveryError>('cleanup_old_recovery_files'),

  showQuickPane: () => invokeResult<void>('show_quick_pane'),
  dismissQuickPane: () => invokeResult<void>('dismiss_quick_pane'),
  toggleQuickPane: () => invokeResult<void>('toggle_quick_pane'),
  getDefaultQuickPaneShortcut: () => invoke<string>('get_default_quick_pane_shortcut'),
  updateQuickPaneShortcut: (shortcut: string | null) =>
    invokeResult<void>('update_quick_pane_shortcut', { shortcut }),

  trayUpdateLang: (lang: string) => invoke<void>('tray_update_lang', { lang }),
}
